export const DataTestIds = {
  user: {
    fulName: "userFullName",
    requestsTab: "requestsTab",
    performanceReviewsTab: "performanceReviewsTab",
    performanceReviewTimelineCard: "performanceReviewTimelineCard",
    addNewPerformanceReviewBtn: "addNewPerformanceReviewBtn",
  },
  common: {
    startDateInput: "startDate",
    endDateInput: "endDate",
    thisMonthBtn: "thisMonthBtn",
    previousMonthBtn: "previousMonthBtn",
  },
  moreToReport: {
    moreToReportBtn: "moreToReportBtn",
    submitButton: "moreToReportSubmitButton",
    onCall: {
      startDateInput: "onCallFormStartDateInput",
      startTimeInput: "onCallFormStartTimeInput",
      endDateInput: "onCallFormEndDateInput",
      endTimeInput: "onCallFormEndTimeInput",
    },
    businessTrip: {
      startDateInput: "businessTripFormStartDateInput",
      startTimeInput: "businessTripFormStartTimeInput",
      endDateInput: "businessTripFormEndDateInput",
      endTimeInput: "businessTripFormEndTimeInput",
      destination: "businessTripDestinationInput",
    },
    tripToOffice: {
      startDateInput: "tripToOfficeFormStartDateInput",
      startTimeInput: "tripToOfficeFormStartTimeInput",
      endDateInput: "tripToOfficeFormEndDateInput",
      endTimeInput: "tripToOfficeFormEndTimeInput",
      mileage: "tripToOfficeMileageInput",
    },
  },
  absence: {
    planAbsenceBtn: "planAbsenceBtn",
    absenceTypeDropdown: "absenceTypeDropdown",
    employeeDropdown: "employeeDropdown",
    startDateInput: "absenceStartDateInput",
    endDateInput: "absenceEndDateInput",
    submitAbsenceBtn: "submitAbsenceBtn",
  },
  dailyReport: {
    addProjectBtn: "addProjectBtn",
    dailyReportBtn: "dailyReportBtn",
    dateInput: "dateInput",
    dailyReportStartTimeInput: "dailyReportStartTimeInput",
    dailyReportEndTimeInput: "dailyReportEndTimeInput",
    projectDropdown: "projectDropdown",
    unassignedActivitiesMessage: "unassignedActivitiesMessage",
    fromHomeBtn: "fromHomeBtn",
    inOfficeBtn: "inOfficeBtn",
    goBackToDashboardBtn: "goBackToDashboardBtn",
    deleteBtn: "deleteBtn",
    headerBreadcrumbs: "dailyHeaderBreadcrumbs",
  },
  reports: {
    employeeIds: "employeeIds",
    projectIds: "projectIds",
    generateBtn: "generateReportButton",
    thisMonthRange: "selectDateRangeForThisMonth",
  },
  performanceReviews: {
    yearInput: "yearInput",
    quarterDropdown: "quarterDropdown",
    answer1RadioInput: "answer1RadioInput",
    answer2RadioInput: "answer2RadioInput",
    answer3RadioInput: "answer3RadioInput",
    answer4RadioInput: "answer4RadioInput",
    saveBtn: "saveBtn",
    editBtn: "editBtn",
  },
  requests: {
    requestsTable: "requestsTable",
    cancelBtn: "cancelRequestBtn",
  },
  activityDashboard: {
    employeeTableNameColumn: "activityDashboardEmployeeTableNameColumn",
    employeeTableLastActivityColumn:
      "activityDashboardEmployeeTableLastActivityColumn",
    todayBusinessTripCell: "todayBusinessTripCell",
  },
};
