export enum SearchParam {
  Action = "action",
  Date = "date",
  Statuses = "statuses",
  StartDate = "startDate",
  EndDate = "endDate",
  Sort = "sort",
  SortActivities = "sortActivities",
  Page = "page",
  Types = "types",
  Search = "search",
  Year = "year",
  SupervisorView = "supervisorView",
  View = "view",
  EmployeeId = "employeeId",
  EmployeeIds = "employeeIds",
  Limit = "limit",
  RequestStatuses = "requestStatuses",
  RequestStatus = "requestStatus",
  UseDate = "useDate",
  Id = "id",
}
