version: "3.9"

services:
  postgres:
    image: "postgres:16.3"
    container_name: skilltrack_postgres_container

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skilltrack_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
